import type { GameMeta } from "./types"

export const gameRegistry: GameMeta[] = [
  {
    id: "snake",
    title: "Snake",
    description: "A modern, minimalistic take on the classic snake game.",
    longDescription: "Control the snake, eat food to grow longer, and avoid hitting the walls or yourself. A timeless arcade classic reimagined with smooth controls and a clean aesthetic.",
    icon: "Grid3X3",
    color: "bg-green-500",
    themeColor: "#22c55e",
    category: "Arcade",
    difficulty: "Easy",
    controls: ["Arrow Keys"],
    tags: ["classic", "arcade", "retro"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "tetris",
    title: "Tetris",
    description: "Stack falling blocks to clear lines and score high.",
    longDescription: "The legendary puzzle game that defined a generation. Arrange falling tetrominoes to create complete lines, which then disappear. The game speeds up as you progress - how long can you survive?",
    icon: "Square",
    color: "bg-purple-500",
    themeColor: "#a855f7",
    category: "Puzzle",
    difficulty: "Medium",
    controls: ["Arrow Keys", "Space"],
    tags: ["classic", "blocks", "high-score"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "pong",
    title: "Pong",
    description: "Modern cyberpunk arcade table tennis with AI difficulty levels and power-ups.",
    longDescription: "Reimagined digital table tennis. Battle against intelligent AI across multiple difficulty levels or challenge a friend in 2-Player mode with neon particle effects, dynamic ball spin, power-ups, and audio synthesis.",
    icon: "Gamepad2",
    color: "bg-blue-500",
    themeColor: "#3b82f6",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["W/S Keys", "Arrow Keys", "Mouse / Touch"],
    tags: ["classic", "2-player", "arcade", "cyberpunk", "powerups"],
    playerCount: "1-2 Players",
    avgPlayTime: "3-5 min",
  },
  {
    id: "flappy",
    title: "Triangle",
    description: "Navigate through obstacles with precise timing.",
    longDescription: "A Flappy Bird-inspired challenge where you guide a triangle through gaps between obstacles. One mistimed tap and it's game over. How far can you go?",
    icon: "Triangle",
    color: "bg-yellow-500",
    themeColor: "#f59e0b",
    category: "Arcade",
    difficulty: "Hard",
    controls: ["Space", "Click"],
    tags: ["timing", "reflex", "high-score"],
    playerCount: "1 Player",
    avgPlayTime: "1-3 min",
  },
  {
    id: "dino",
    title: "Sheep Run",
    description: "Jump over hurdles, duck under flying eagles, collect power-ups, and run wild!",
    longDescription: "A high-octane modern endless runner starring a fluffy sheep! Jump, double-jump, and duck under hazards across 4 distinct difficulty modes (Peaceful Pasture, Wild Meadow, Wolf Mountain, Stormy Ridge). Collect golden clovers, invincibility shields, and score multipliers as day turns to night.",
    icon: "PawPrint",
    color: "bg-emerald-600",
    themeColor: "#10b981",
    category: "Arcade",
    difficulty: "Variable",
    controls: ["Space / Up / W (Jump)", "Down / S (Duck)"],
    tags: ["runner", "endless", "arcade", "sheep", "power-ups"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "breakout",
    title: "Breakout",
    description: "Break all the bricks with your ball and paddle.",
    longDescription: "Smash through colorful brick walls with your trusty paddle and ball. Each level presents a new challenge as the bricks get tougher and the ball gets faster.",
    icon: "Zap",
    color: "bg-orange-500",
    themeColor: "#f97316",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Mouse"],
    tags: ["brick-breaker", "classic", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "reaction",
    title: "Reaction Time",
    description: "Test your reflexes. How fast can you click?",
    longDescription: "Put your reflexes to the ultimate test. Watch the screen, wait for the signal, and click as fast as you can. Compare your reaction time against world averages and try to beat your personal best.",
    icon: "Timer",
    color: "bg-red-500",
    themeColor: "#ef4444",
    category: "Action",
    difficulty: "Easy",
    controls: ["Mouse Click", "Tap"],
    tags: ["reflex", "speed", "benchmark"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "color-match",
    title: "Color Match",
    description: "Match the target color as fast as you can!",
    longDescription: "Train your color perception and speed. A target color is displayed, and you must pick the matching shade from multiple options. The faster you match, the higher your score.",
    icon: "Palette",
    color: "bg-pink-500",
    themeColor: "#ec4899",
    category: "Action",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["color", "speed", "perception"],
    playerCount: "1 Player",
    avgPlayTime: "2-3 min",
  },
  {
    id: "space-invaders",
    title: "Space Invaders",
    description: "Defend Earth from waves of alien invaders.",
    longDescription: "Classic arcade shooter action! Pilot your spaceship, dodge enemy fire, and blast waves of invading aliens. Each wave gets faster and more challenging.",
    icon: "Rocket",
    color: "bg-cyan-500",
    themeColor: "#06b6d4",
    category: "Action",
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Space"],
    tags: ["shooter", "classic", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "simon-says",
    title: "Simon Says",
    description: "Watch the pattern and repeat it back - test your memory!",
    longDescription: "The classic memory game with a modern twist. Watch as colors light up in sequence, then repeat the pattern. Each round adds one more step to the sequence - how many can you remember?",
    icon: "Brain",
    color: "bg-purple-600",
    themeColor: "#9333ea",
    category: "Action",
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["memory", "pattern", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "whack-a-mole",
    title: "Whack-a-Mole",
    description: "Quick reflexes needed - whack the moles before they hide!",
    longDescription: "A frantic reflex game where moles pop up randomly and you must whack them before they disappear. Choose your difficulty and try to beat the high score.",
    icon: "Target",
    color: "bg-green-500",
    themeColor: "#22c55e",
    category: "Action",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["reflex", "fun", "casual"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "2048",
    title: "2048",
    description: "Slide numbered tiles to reach 2048 - addictive puzzle challenge!",
    longDescription: "The addictive puzzle game that took the world by storm. Swipe to combine matching numbers and work your way up to the elusive 2048 tile. Strategic thinking meets simple gameplay.",
    icon: "Grid3X3",
    color: "bg-amber-500",
    themeColor: "#f59e0b",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Arrow Keys", "Swipe"],
    tags: ["numbers", "sliding", "addictive"],
    playerCount: "1 Player",
    avgPlayTime: "5-15 min",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description: "Match pairs of cards with memory.",
    longDescription: "Test and improve your memory by flipping cards to find matching pairs. Multiple difficulty levels let you challenge yourself with larger grids and more complex patterns.",
    icon: "Brain",
    color: "bg-pink-500",
    themeColor: "#ec4899",
    category: "Puzzle",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["memory", "matching", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "word-scramble",
    title: "Word Scramble",
    description: "Unscramble letters to form words quickly.",
    longDescription: "Put your vocabulary to the test! Letters are scrambled and you must rearrange them to form the correct word. Race against the clock and build your word power.",
    icon: "BookOpen",
    color: "bg-purple-500",
    themeColor: "#8b5cf6",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard"],
    tags: ["words", "vocabulary", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Clear the board without hitting mines.",
    longDescription: "The classic logic puzzle game. Use number clues to deduce where mines are hidden and flag them. Clear all safe squares without detonating a mine to win.",
    icon: "Bomb",
    color: "bg-gray-700",
    themeColor: "#374151",
    category: "Strategy",
    difficulty: "Medium",
    controls: ["Left Click", "Right Click"],
    tags: ["logic", "deduction", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "tic-tac-toe",
    title: "Tic Tac Toe",
    description: "Classic strategy game - get three in a row to win!",
    longDescription: "The timeless game of X's and O's. Challenge an AI opponent that uses the minimax algorithm - it's impossible to beat! Can you at least force a draw?",
    icon: "Grid3X3",
    color: "bg-emerald-500",
    themeColor: "#10b981",
    category: "Strategy",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["classic", "AI", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "connect-four",
    title: "Connect Four",
    description: "Drop pieces to get four in a row - play vs friends or CPU.",
    longDescription: "Drop colored discs into a vertical grid and be the first to connect four in a row - horizontally, vertically, or diagonally. Challenge the AI or play with a friend locally.",
    icon: "Circle",
    color: "bg-red-500",
    themeColor: "#ef4444",
    category: "Strategy",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["board", "strategy", "multiplayer"],
    playerCount: "1-2 Players",
    avgPlayTime: "5-10 min",
  },
  {
    id: "orbit-defense",
    title: "Orbit Defense",
    description: "Strategic tower defense in the vastness of space.",
    longDescription: "Defend your orbital station from waves of enemy ships. Place defensive turrets strategically around your station and upgrade them to withstand increasingly powerful attacks.",
    icon: "Target",
    color: "bg-indigo-500",
    themeColor: "#6366f1",
    category: "Strategy",
    difficulty: "Hard",
    controls: ["Mouse Click"],
    tags: ["tower-defense", "space", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "10-15 min",
  },
  {
    id: "coin-collector",
    title: "Coin Collector",
    description: "Jump and collect coins in a platformer adventure.",
    longDescription: "Run, jump, and collect as many coins as you can in this fast-paced platformer. Dodge obstacles, time your jumps perfectly, and chase that high score.",
    icon: "Coins",
    color: "bg-yellow-500",
    themeColor: "#f59e0b",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Arrow Keys", "Space"],
    tags: ["platformer", "collector", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "bubble-pop",
    title: "Bubble Pop",
    description: "Pop colorful bubbles and build combos.",
    longDescription: "A satisfying bubble-popping experience! Bubbles float up from the bottom and you must pop them before they escape. Chain combos for bonus points and compete for the highest score.",
    icon: "Sparkles",
    color: "bg-cyan-500",
    themeColor: "#4ecdc4",
    category: "Arcade",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["casual", "colorful", "relaxing"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "typing-speed",
    title: "Typing Speed Test",
    description: "Test your typing speed and accuracy with timed challenges.",
    longDescription: "Measure your words per minute and typing accuracy. Choose from various difficulty levels and text passages. Track your progress over time and compete with friends.",
    icon: "Keyboard",
    color: "bg-violet-500",
    themeColor: "#8b5cf6",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard"],
    tags: ["typing", "speed", "words"],
    playerCount: "1 Player",
    avgPlayTime: "1-3 min",
  },
  {
    id: "sudoku",
    title: "Sudoku",
    description: "Fill the grid so every row, column, and box contains digits 1-9.",
    longDescription: "The world's most popular number puzzle. Use logic and deduction to fill the 9x9 grid so each row, column, and 3x3 box contains the digits 1 through 9 exactly once.",
    icon: "Grid3X3",
    color: "bg-teal-500",
    themeColor: "#14b8a6",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click", "Keyboard"],
    tags: ["numbers", "logic", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "10-20 min",
  },
  {
    id: "pacman",
    title: "Pac-Man",
    description: "Navigate the maze, eat dots, and avoid ghosts in this arcade classic.",
    longDescription: "The legendary arcade game reimagined. Guide Pac-Man through the maze, eat all the dots, and avoid the colorful ghosts. Power pellets let you turn the tables and chase the ghosts!",
    icon: "Circle",
    color: "bg-yellow-400",
    themeColor: "#facc15",
    category: "Arcade",
    isNew: true,
    difficulty: "Medium",
    controls: ["Arrow Keys"],
    tags: ["classic", "maze", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "solitaire",
    title: "Solitaire",
    description: "The classic card game - stack suits and clear the table.",
    longDescription: "The beloved solo card game. Arrange cards in descending order alternating colors, and build up foundation piles by suit. A perfect game for relaxing and sharpening your strategic thinking.",
    icon: "LayoutGrid",
    color: "bg-blue-700",
    themeColor: "#1d4ed8",
    category: "Card",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click", "Drag & Drop"],
    tags: ["cards", "classic", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "10-15 min",
  },
  {
    id: "trivia-quiz",
    title: "Trivia Quiz",
    description: "Test your knowledge across multiple categories in this quiz challenge.",
    longDescription: "Challenge your general knowledge with questions spanning history, science, sports, entertainment, and more. Answer quickly for bonus points and climb the leaderboard!",
    icon: "Brain",
    color: "bg-rose-500",
    themeColor: "#f43f5e",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["quiz", "knowledge", "trivia"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "blackjack",
    title: "Blackjack",
    description: "Beat the dealer in this classic casino card game - get to 21!",
    longDescription: "The timeless casino card game. Place your bet, get dealt two cards, and decide whether to hit or stand. Beat the dealer without going over 21 and walk away with the winnings.",
    icon: "LayoutGrid",
    color: "bg-red-600",
    themeColor: "#dc2626",
    category: "Card",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["cards", "casino", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "poker",
    title: "Video Poker",
    description: "5-card draw poker - hold your best cards and draw for a winning hand.",
    longDescription: "Classic video poker with full hand evaluation. Deal five cards, hold the ones you want to keep, and draw replacements to make the best possible poker hand. Score big with Royal Flushes and Straight Flushes.",
    icon: "LayoutGrid",
    color: "bg-violet-600",
    themeColor: "#7c3aed",
    category: "Card",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["cards", "poker", "casino"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "hangman",
    title: "Hangman",
    description: "Guess the word letter by letter before the stickman is complete.",
    longDescription: "The classic word guessing game. Each wrong guess brings the stickman closer to the gallows. Test your vocabulary and deduction skills across a variety of word categories.",
    icon: "BookOpen",
    color: "bg-purple-500",
    themeColor: "#8b5cf6",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["words", "guessing", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "word-search",
    title: "Word Search",
    description: "Find hidden words in a grid of letters - drag to select and score.",
    longDescription: "Scan the letter grid and find hidden programming-themed words in all directions. Click and drag to highlight words. Find them all to complete the puzzle.",
    icon: "Search",
    color: "bg-sky-500",
    themeColor: "#0ea5e9",
    category: "Word",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click", "Drag"],
    tags: ["words", "search", "puzzle"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "checkers",
    title: "Checkers",
    description: "Classic board game - jump to capture all opponent pieces.",
    longDescription: "The timeless strategy board game. Move your pieces diagonally, jump over opponent pieces to capture them, and reach the far side to crown your kings. Challenge the AI and prove your strategic prowess.",
    icon: "Grid3X3",
    color: "bg-red-600",
    themeColor: "#dc2626",
    category: "Strategy",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["board", "classic", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "battleship",
    title: "Battleship",
    description: "Place your fleet and sink the enemy ships before they sink yours.",
    longDescription: "The classic naval combat game. Strategically place your ships on the grid, then take turns firing at the enemy's waters. Use deduction to locate and destroy all enemy vessels before the AI sinks your fleet.",
    icon: "Ship",
    color: "bg-blue-800",
    themeColor: "#1e40af",
    category: "Strategy",
    isNew: true,
    difficulty: "Hard",
    controls: ["Mouse Click"],
    tags: ["naval", "strategy", "deduction"],
    playerCount: "1 Player",
    avgPlayTime: "10-15 min",
  },
  {
    id: "asteroids",
    title: "Asteroids",
    description: "Pilot your spaceship through an asteroid field - blast them to survive!",
    longDescription: "The legendary arcade space shooter. Rotate and thrust your spaceship, fire at incoming asteroids, and survive as long as you can. Large asteroids split into smaller ones when destroyed - stay sharp!",
    icon: "Rocket",
    color: "bg-cyan-500",
    themeColor: "#06b6d4",
    category: "Action",
    isNew: true,
    difficulty: "Hard",
    controls: ["Arrow Keys", "Space"],
    tags: ["shooter", "space", "arcade", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "match3",
    title: "Match-3",
    description: "Swap adjacent gems to match 3 in a row and score combos.",
    longDescription: "A satisfying puzzle game where you swap adjacent gems to create lines of 3 or more matching colors. Chain reactions and cascading combos earn bonus points. Clear the board to maximize your score before you run out of moves.",
    icon: "Sparkles",
    color: "bg-teal-500",
    themeColor: "#14b8a6",
    category: "Puzzle",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["matching", "puzzle", "casual"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "stack-tower",
    title: "Stack Tower",
    description: "Time each drop to build the tallest tower you can.",
    longDescription: "A block slides back and forth above your tower - drop it at the right moment to land it squarely. Anything hanging over the edge is trimmed away, so sloppy timing shrinks your platform until there is nothing left to land on.",
    icon: "Square",
    color: "bg-orange-600",
    themeColor: "#c2410c",
    category: "Arcade",
    isNew: true,
    difficulty: "Easy",
    controls: ["Space", "Click"],
    tags: ["timing", "precision", "high-score"],
    playerCount: "1 Player",
    avgPlayTime: "2-4 min",
  },
  {
    id: "lane-racer",
    title: "Lane Racer",
    description: "Weave through four lanes of traffic at increasing speed.",
    longDescription: "An endless highway racer. Switch lanes to slip past oncoming cars while the road scrolls faster and faster. There is always one clear lane - the trick is spotting it in time.",
    icon: "Zap",
    color: "bg-rose-600",
    themeColor: "#be123c",
    category: "Arcade",
    isNew: true,
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Click"],
    tags: ["racing", "endless", "reflex"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "road-crossing",
    title: "Road Crossing",
    description: "Hop across busy lanes to reach the far side safely.",
    longDescription: "A Frogger-style dash across traffic. Move one square at a time between gaps in the cars, use the safe strips to catch your breath, and reach the goal line. Three lives, and the lanes reshuffle every time you make it across.",
    icon: "Target",
    color: "bg-lime-700",
    themeColor: "#4d7c0f",
    category: "Arcade",
    isNew: true,
    difficulty: "Medium",
    controls: ["Arrow Keys", "Click"],
    tags: ["classic", "timing", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "3-6 min",
  },
  {
    id: "sliding-puzzle",
    title: "Sliding Puzzle",
    description: "Slide numbered tiles back into order - 3x3 up to 5x5.",
    longDescription: "The classic 15-puzzle, with three board sizes. Slide tiles into the single empty space to restore numerical order. Every shuffle is generated by walking the blank space backwards, so each puzzle is guaranteed solvable.",
    icon: "LayoutGrid",
    color: "bg-indigo-600",
    themeColor: "#4338ca",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["classic", "logic", "tiles"],
    playerCount: "1 Player",
    avgPlayTime: "5-15 min",
  },
  {
    id: "lights-out",
    title: "Lights Out",
    description: "Switch off every light - but each press flips its neighbours too.",
    longDescription: "A deceptively tricky logic puzzle. Pressing a light toggles it along with the four lights around it, so clearing the board takes planning rather than luck. Each level you solve scrambles the next one a little further.",
    icon: "Zap",
    color: "bg-amber-700",
    themeColor: "#b45309",
    category: "Puzzle",
    isNew: true,
    difficulty: "Hard",
    controls: ["Mouse Click"],
    tags: ["logic", "levels", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "tower-of-hanoi",
    title: "Tower of Hanoi",
    description: "Move the whole stack of discs across, one disc at a time.",
    longDescription: "The classic recursion puzzle. Shift every disc to the right-hand peg, moving one at a time and never placing a larger disc on a smaller one. Three discs take seven moves; six discs take sixty-three.",
    icon: "LayoutGrid",
    color: "bg-fuchsia-700",
    themeColor: "#a21caf",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["classic", "logic", "recursion"],
    playerCount: "1 Player",
    avgPlayTime: "3-10 min",
  },
  {
    id: "reversi",
    title: "Reversi",
    description: "Flank the AI's discs to flip them and own the board.",
    longDescription: "Also known as Othello. Place a disc so it traps a line of your opponent's between two of yours, and the whole line flips to your colour. The AI values corners and edges highly, so think about position rather than raw disc count.",
    icon: "Circle",
    color: "bg-emerald-700",
    themeColor: "#047857",
    category: "Strategy",
    isNew: true,
    difficulty: "Hard",
    controls: ["Mouse Click"],
    tags: ["board", "AI", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "8-15 min",
  },
  {
    id: "gomoku",
    title: "Gomoku",
    description: "Get five stones in a row before the AI does.",
    longDescription: "Five-in-a-row on a 13x13 board. The rules take five seconds to learn, but the tactics run deep - the AI weighs its own threats against yours, so an unblocked line of three will not survive long.",
    icon: "Grid3X3",
    color: "bg-stone-700",
    themeColor: "#44403c",
    category: "Strategy",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["board", "AI", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "5-12 min",
  },
  {
    id: "dots-and-boxes",
    title: "Dots & Boxes",
    description: "Draw lines to close squares - and claim another turn.",
    longDescription: "A pen-and-paper classic. Take turns drawing a line between two adjacent dots; completing a square claims it and earns you an immediate extra turn. The endgame is all about chains - hand the AI one box and it may take six.",
    icon: "Grid3X3",
    color: "bg-sky-700",
    themeColor: "#0369a1",
    category: "Strategy",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["paper-game", "AI", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "aim-trainer",
    title: "Aim Trainer",
    description: "Click 25 targets as fast as you can - accuracy counts.",
    longDescription: "A precision drill used by competitive players. Targets appear one at a time at random positions and sizes; hit all 25 while keeping your accuracy high. Reports your average reaction time, fastest hit, and hit rate.",
    icon: "Target",
    color: "bg-red-700",
    themeColor: "#b91c1c",
    category: "Action",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["reflex", "precision", "benchmark"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "rhythm-tap",
    title: "Rhythm Tap",
    description: "Hit falling notes in time across four lanes.",
    longDescription: "Notes stream down four lanes toward the hit line - tap D, F, J, or K at the right moment. Land them dead-centre for a Perfect, build a combo for a score multiplier, and try to survive as the tempo climbs.",
    icon: "Sparkles",
    color: "bg-fuchsia-700",
    themeColor: "#a21caf",
    category: "Action",
    isNew: true,
    difficulty: "Hard",
    controls: ["D/F/J/K Keys", "Tap"],
    tags: ["rhythm", "music", "timing"],
    playerCount: "1 Player",
    avgPlayTime: "2-4 min",
  },
  {
    id: "meteor-dodge",
    title: "Meteor Dodge",
    description: "Pilot your ship through a thickening meteor shower.",
    longDescription: "Pure survival. Steer left and right - with the keyboard or by dragging - as meteors of every size rain down and ricochet off the walls. There is no weapon here; the only way to score is to stay alive.",
    icon: "Rocket",
    color: "bg-orange-700",
    themeColor: "#c2410c",
    category: "Action",
    isNew: true,
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Drag"],
    tags: ["space", "survival", "reflex"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "card-war",
    title: "Card War",
    description: "High card takes the pile - ties mean war.",
    longDescription: "The deck is split evenly and every flip is a showdown. The higher card claims both, and when ranks tie each side buries a card and the pot rides on the next flip. Play until one deck runs dry.",
    icon: "LayoutGrid",
    color: "bg-slate-700",
    themeColor: "#1e293b",
    category: "Card",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["cards", "classic", "casual"],
    playerCount: "1 Player",
    avgPlayTime: "3-8 min",
  },
  {
    id: "hi-lo",
    title: "Hi-Lo",
    description: "Call the next card higher or lower - build the streak.",
    longDescription: "A pure nerve game. Look at the current card and predict whether the next one is higher or lower. Each correct call in a row is worth more than the last, matching ranks are a harmless push, and one wrong call ends the run.",
    icon: "TrendingUp",
    color: "bg-green-700",
    themeColor: "#15803d",
    category: "Card",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["cards", "streak", "casual"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "crazy-eights",
    title: "Crazy Eights",
    description: "Shed your hand by matching suit or rank - eights are wild.",
    longDescription: "The shedding game that inspired Uno. Play a card matching the discard pile's suit or rank, draw when you are stuck, and use any 8 as a wild card to declare a new suit. First to empty their hand wins.",
    icon: "LayoutGrid",
    color: "bg-violet-700",
    themeColor: "#6d28d9",
    category: "Card",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["cards", "classic", "AI"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "wordle",
    title: "Word Guess",
    description: "Six tries to find the hidden five-letter word.",
    longDescription: "Guess the five-letter word in six attempts. Green marks a letter in the right spot, yellow means it is in the word but elsewhere, grey rules it out. The keyboard tracks everything you have learned so far.",
    icon: "BookOpen",
    color: "bg-green-700",
    themeColor: "#15803d",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard", "Mouse Click"],
    tags: ["words", "deduction", "daily"],
    playerCount: "1 Player",
    avgPlayTime: "3-6 min",
  },
  {
    id: "anagram-hunt",
    title: "Anagram Hunt",
    description: "Find every word hiding in six scrambled letters.",
    longDescription: "Ninety seconds, six letters, and a long list of words buried inside them. Longer finds score more, and using all six letters at once pays a big bonus. Time left over converts into extra points if you clear the board.",
    icon: "Search",
    color: "bg-orange-700",
    themeColor: "#c2410c",
    category: "Word",
    isNew: true,
    difficulty: "Hard",
    controls: ["Keyboard"],
    tags: ["words", "timed", "vocabulary"],
    playerCount: "1 Player",
    avgPlayTime: "2-4 min",
  },
  {
    id: "spelling-bee",
    title: "Spelling Bee",
    description: "Build words from seven letters - the centre one is mandatory.",
    longDescription: "A honeycomb of seven letters. Every word must be at least four letters long and must include the centre letter; letters may be reused freely. Find a word that uses all seven for a pangram bonus and climb from Beginner to Genius.",
    icon: "Sparkles",
    color: "bg-yellow-600",
    themeColor: "#ca8a04",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard", "Mouse Click"],
    tags: ["words", "vocabulary", "puzzle"],
    playerCount: "1 Player",
    avgPlayTime: "5-15 min",
  },
]

export const categories: Array<{ id: GameMeta["category"]; label: string; icon: string }> = [
  { id: "All", label: "All Games", icon: "Gamepad2" },
  { id: "Arcade", label: "Arcade", icon: "Zap" },
  { id: "Puzzle", label: "Puzzle", icon: "Brain" },
  { id: "Strategy", label: "Strategy", icon: "Target" },
  { id: "Action", label: "Action", icon: "Timer" },
  { id: "Card", label: "Card Games", icon: "LayoutGrid" },
  { id: "Word", label: "Word Games", icon: "BookOpen" },
]

export function getGameById(id: string): GameMeta | undefined {
  return gameRegistry.find((g) => g.id === id)
}

export function getGamesByCategory(category: GameMeta["category"]): GameMeta[] {
  if (category === "All") return gameRegistry
  return gameRegistry.filter((g) => g.category === category)
}

export function getNewGames(): GameMeta[] {
  return gameRegistry.filter((g) => g.isNew)
}

export function getCategories(): GameMeta["category"][] {
  return [...new Set(gameRegistry.map((g) => g.category))]
}
