import type { GameMeta } from "./types"

export const gameRegistry: GameMeta[] = [
  {
    id: "snake",
    title: "Snake",
    description: "A modern, minimalistic take on the classic snake game.",
    longDescription: "Control the snake, eat food to grow longer, and avoid hitting the walls or yourself. A timeless arcade classic reimagined with smooth controls and a clean aesthetic.",
    icon: "Grid3X3",
    color: "bg-green-500",
    themeColor: "#22c55e",
    category: "Arcade",
    difficulty: "Easy",
    controls: ["Arrow Keys"],
    tags: ["classic", "arcade", "retro"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "tetris",
    title: "Tetris",
    description: "Stack falling blocks to clear lines and score high.",
    longDescription: "The legendary puzzle game that defined a generation. Arrange falling tetrominoes to create complete lines, which then disappear. The game speeds up as you progress - how long can you survive?",
    icon: "Square",
    color: "bg-purple-500",
    themeColor: "#a855f7",
    category: "Puzzle",
    difficulty: "Medium",
    controls: ["Arrow Keys", "Space"],
    tags: ["classic", "blocks", "high-score"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "pong",
    title: "Pong",
    description: "The timeless arcade classic. Play against an AI opponent.",
    longDescription: "The game that started it all. Battle against an increasingly skilled AI opponent in this digital table tennis match. First to 10 points wins.",
    icon: "Gamepad2",
    color: "bg-blue-500",
    themeColor: "#3b82f6",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Up/Down Arrow", "W/S Keys"],
    tags: ["classic", "2-player", "retro"],
    playerCount: "1-2 Players",
    avgPlayTime: "3-5 min",
  },
  {
    id: "flappy",
    title: "Triangle",
    description: "Navigate through obstacles with precise timing.",
    longDescription: "A Flappy Bird-inspired challenge where you guide a triangle through gaps between obstacles. One mistimed tap and it's game over. How far can you go?",
    icon: "Triangle",
    color: "bg-yellow-500",
    themeColor: "#f59e0b",
    category: "Arcade",
    difficulty: "Hard",
    controls: ["Space", "Click"],
    tags: ["timing", "reflex", "high-score"],
    playerCount: "1 Player",
    avgPlayTime: "1-3 min",
  },
  {
    id: "dino",
    title: "Sheep Run",
    description: "Jump over cacti and dodge flying birds.",
    longDescription: "An endless runner inspired by the Chrome dinosaur game. Jump over obstacles, duck under birds, and see how far you can run in this charming pixel-style adventure.",
    icon: "PawPrint",
    color: "bg-gray-700",
    themeColor: "#374151",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Space", "Up Arrow"],
    tags: ["runner", "endless", "pixel"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "breakout",
    title: "Breakout",
    description: "Break all the bricks with your ball and paddle.",
    longDescription: "Smash through colorful brick walls with your trusty paddle and ball. Each level presents a new challenge as the bricks get tougher and the ball gets faster.",
    icon: "Zap",
    color: "bg-orange-500",
    themeColor: "#f97316",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Mouse"],
    tags: ["brick-breaker", "classic", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "reaction",
    title: "Reaction Time",
    description: "Test your reflexes. How fast can you click?",
    longDescription: "Put your reflexes to the ultimate test. Watch the screen, wait for the signal, and click as fast as you can. Compare your reaction time against world averages and try to beat your personal best.",
    icon: "Timer",
    color: "bg-red-500",
    themeColor: "#ef4444",
    category: "Action",
    difficulty: "Easy",
    controls: ["Mouse Click", "Tap"],
    tags: ["reflex", "speed", "benchmark"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "color-match",
    title: "Color Match",
    description: "Match the target color as fast as you can!",
    longDescription: "Train your color perception and speed. A target color is displayed, and you must pick the matching shade from multiple options. The faster you match, the higher your score.",
    icon: "Palette",
    color: "bg-pink-500",
    themeColor: "#ec4899",
    category: "Action",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["color", "speed", "perception"],
    playerCount: "1 Player",
    avgPlayTime: "2-3 min",
  },
  {
    id: "space-invaders",
    title: "Space Invaders",
    description: "Defend Earth from waves of alien invaders.",
    longDescription: "Classic arcade shooter action! Pilot your spaceship, dodge enemy fire, and blast waves of invading aliens. Each wave gets faster and more challenging.",
    icon: "Rocket",
    color: "bg-cyan-500",
    themeColor: "#06b6d4",
    category: "Action",
    difficulty: "Medium",
    controls: ["Left/Right Arrow", "Space"],
    tags: ["shooter", "classic", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "simon-says",
    title: "Simon Says",
    description: "Watch the pattern and repeat it back - test your memory!",
    longDescription: "The classic memory game with a modern twist. Watch as colors light up in sequence, then repeat the pattern. Each round adds one more step to the sequence - how many can you remember?",
    icon: "Brain",
    color: "bg-purple-600",
    themeColor: "#9333ea",
    category: "Action",
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["memory", "pattern", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "whack-a-mole",
    title: "Whack-a-Mole",
    description: "Quick reflexes needed - whack the moles before they hide!",
    longDescription: "A frantic reflex game where moles pop up randomly and you must whack them before they disappear. Choose your difficulty and try to beat the high score.",
    icon: "Target",
    color: "bg-green-500",
    themeColor: "#22c55e",
    category: "Action",
    isNew: true,
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["reflex", "fun", "casual"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "2048",
    title: "2048",
    description: "Slide numbered tiles to reach 2048 - addictive puzzle challenge!",
    longDescription: "The addictive puzzle game that took the world by storm. Swipe to combine matching numbers and work your way up to the elusive 2048 tile. Strategic thinking meets simple gameplay.",
    icon: "Grid3X3",
    color: "bg-amber-500",
    themeColor: "#f59e0b",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Arrow Keys", "Swipe"],
    tags: ["numbers", "sliding", "addictive"],
    playerCount: "1 Player",
    avgPlayTime: "5-15 min",
  },
  {
    id: "memory-match",
    title: "Memory Match",
    description: "Match pairs of cards with memory.",
    longDescription: "Test and improve your memory by flipping cards to find matching pairs. Multiple difficulty levels let you challenge yourself with larger grids and more complex patterns.",
    icon: "Brain",
    color: "bg-pink-500",
    themeColor: "#ec4899",
    category: "Puzzle",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["memory", "matching", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "word-scramble",
    title: "Word Scramble",
    description: "Unscramble letters to form words quickly.",
    longDescription: "Put your vocabulary to the test! Letters are scrambled and you must rearrange them to form the correct word. Race against the clock and build your word power.",
    icon: "BookOpen",
    color: "bg-purple-500",
    themeColor: "#8b5cf6",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard"],
    tags: ["words", "vocabulary", "brain-training"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Clear the board without hitting mines.",
    longDescription: "The classic logic puzzle game. Use number clues to deduce where mines are hidden and flag them. Clear all safe squares without detonating a mine to win.",
    icon: "Bomb",
    color: "bg-gray-700",
    themeColor: "#374151",
    category: "Strategy",
    difficulty: "Medium",
    controls: ["Left Click", "Right Click"],
    tags: ["logic", "deduction", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "tic-tac-toe",
    title: "Tic Tac Toe",
    description: "Classic strategy game - get three in a row to win!",
    longDescription: "The timeless game of X's and O's. Challenge an AI opponent that uses the minimax algorithm - it's impossible to beat! Can you at least force a draw?",
    icon: "Grid3X3",
    color: "bg-emerald-500",
    themeColor: "#10b981",
    category: "Strategy",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["classic", "AI", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "1-2 min",
  },
  {
    id: "connect-four",
    title: "Connect Four",
    description: "Drop pieces to get four in a row - play vs friends or CPU.",
    longDescription: "Drop colored discs into a vertical grid and be the first to connect four in a row - horizontally, vertically, or diagonally. Challenge the AI or play with a friend locally.",
    icon: "Circle",
    color: "bg-red-500",
    themeColor: "#ef4444",
    category: "Strategy",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["board", "strategy", "multiplayer"],
    playerCount: "1-2 Players",
    avgPlayTime: "5-10 min",
  },
  {
    id: "orbit-defense",
    title: "Orbit Defense",
    description: "Strategic tower defense in the vastness of space.",
    longDescription: "Defend your orbital station from waves of enemy ships. Place defensive turrets strategically around your station and upgrade them to withstand increasingly powerful attacks.",
    icon: "Target",
    color: "bg-indigo-500",
    themeColor: "#6366f1",
    category: "Strategy",
    difficulty: "Hard",
    controls: ["Mouse Click"],
    tags: ["tower-defense", "space", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "10-15 min",
  },
  {
    id: "coin-collector",
    title: "Coin Collector",
    description: "Jump and collect coins in a platformer adventure.",
    longDescription: "Run, jump, and collect as many coins as you can in this fast-paced platformer. Dodge obstacles, time your jumps perfectly, and chase that high score.",
    icon: "Coins",
    color: "bg-yellow-500",
    themeColor: "#f59e0b",
    category: "Arcade",
    difficulty: "Medium",
    controls: ["Arrow Keys", "Space"],
    tags: ["platformer", "collector", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
  {
    id: "bubble-pop",
    title: "Bubble Pop",
    description: "Pop colorful bubbles and build combos.",
    longDescription: "A satisfying bubble-popping experience! Bubbles float up from the bottom and you must pop them before they escape. Chain combos for bonus points and compete for the highest score.",
    icon: "Sparkles",
    color: "bg-cyan-500",
    themeColor: "#4ecdc4",
    category: "Arcade",
    difficulty: "Easy",
    controls: ["Mouse Click"],
    tags: ["casual", "colorful", "relaxing"],
    playerCount: "1 Player",
    avgPlayTime: "2-5 min",
  },
  {
    id: "typing-speed",
    title: "Typing Speed Test",
    description: "Test your typing speed and accuracy with timed challenges.",
    longDescription: "Measure your words per minute and typing accuracy. Choose from various difficulty levels and text passages. Track your progress over time and compete with friends.",
    icon: "Keyboard",
    color: "bg-violet-500",
    themeColor: "#8b5cf6",
    category: "Word",
    isNew: true,
    difficulty: "Medium",
    controls: ["Keyboard"],
    tags: ["typing", "speed", "words"],
    playerCount: "1 Player",
    avgPlayTime: "1-3 min",
  },
  {
    id: "sudoku",
    title: "Sudoku",
    description: "Fill the grid so every row, column, and box contains digits 1-9.",
    longDescription: "The world's most popular number puzzle. Use logic and deduction to fill the 9x9 grid so each row, column, and 3x3 box contains the digits 1 through 9 exactly once.",
    icon: "Grid3X3",
    color: "bg-teal-500",
    themeColor: "#14b8a6",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click", "Keyboard"],
    tags: ["numbers", "logic", "classic"],
    playerCount: "1 Player",
    avgPlayTime: "10-20 min",
  },
  {
    id: "pacman",
    title: "Pac-Man",
    description: "Navigate the maze, eat dots, and avoid ghosts in this arcade classic.",
    longDescription: "The legendary arcade game reimagined. Guide Pac-Man through the maze, eat all the dots, and avoid the colorful ghosts. Power pellets let you turn the tables and chase the ghosts!",
    icon: "Circle",
    color: "bg-yellow-400",
    themeColor: "#facc15",
    category: "Arcade",
    isNew: true,
    difficulty: "Medium",
    controls: ["Arrow Keys"],
    tags: ["classic", "maze", "arcade"],
    playerCount: "1 Player",
    avgPlayTime: "5-10 min",
  },
  {
    id: "solitaire",
    title: "Solitaire",
    description: "The classic card game - stack suits and clear the table.",
    longDescription: "The beloved solo card game. Arrange cards in descending order alternating colors, and build up foundation piles by suit. A perfect game for relaxing and sharpening your strategic thinking.",
    icon: "LayoutGrid",
    color: "bg-blue-700",
    themeColor: "#1d4ed8",
    category: "Card",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click", "Drag & Drop"],
    tags: ["cards", "classic", "strategy"],
    playerCount: "1 Player",
    avgPlayTime: "10-15 min",
  },
  {
    id: "trivia-quiz",
    title: "Trivia Quiz",
    description: "Test your knowledge across multiple categories in this quiz challenge.",
    longDescription: "Challenge your general knowledge with questions spanning history, science, sports, entertainment, and more. Answer quickly for bonus points and climb the leaderboard!",
    icon: "Brain",
    color: "bg-rose-500",
    themeColor: "#f43f5e",
    category: "Puzzle",
    isNew: true,
    difficulty: "Medium",
    controls: ["Mouse Click"],
    tags: ["quiz", "knowledge", "trivia"],
    playerCount: "1 Player",
    avgPlayTime: "3-5 min",
  },
]

export const categories: Array<{ id: GameMeta["category"]; label: string; icon: string }> = [
  { id: "All", label: "All Games", icon: "Gamepad2" },
  { id: "Arcade", label: "Arcade", icon: "Zap" },
  { id: "Puzzle", label: "Puzzle", icon: "Brain" },
  { id: "Strategy", label: "Strategy", icon: "Target" },
  { id: "Action", label: "Action", icon: "Timer" },
  { id: "Card", label: "Card Games", icon: "LayoutGrid" },
  { id: "Word", label: "Word Games", icon: "BookOpen" },
]

export function getGameById(id: string): GameMeta | undefined {
  return gameRegistry.find((g) => g.id === id)
}

export function getGamesByCategory(category: GameMeta["category"]): GameMeta[] {
  if (category === "All") return gameRegistry
  return gameRegistry.filter((g) => g.category === category)
}

export function getNewGames(): GameMeta[] {
  return gameRegistry.filter((g) => g.isNew)
}

export function getCategories(): GameMeta["category"][] {
  return [...new Set(gameRegistry.map((g) => g.category))]
}
